name: fisiovision
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.0-247.0.dev

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.2
  google_mlkit_pose_detection: ^0.14.0
  lucide_icons_flutter: ^3.1.4
  fluttertoast: ^9.0.0
  permission_handler: ^12.0.1
  flutter_riverpod: ^3.0.3
  shared_preferences: ^2.5.3
  go_router: ^17.0.0
  dio: ^5.9.0
  dotenv: ^4.2.0
  flutter_dotenv: ^6.0.0
  jwt_decoder: ^2.0.1
  formz: ^0.8.0
  http: ^1.1.0 # Para llamadas a API
  riverpod: ^3.0.3
  provider: ^6.1.5+1
<<<<<<< HEAD
=======
  intl: ^0.20.2

>>>>>>> f5ca5ce40f7db0a6c72bd4e6ec97bb49a7be7551
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
